use crate::rust_alloc::vec::Vec;
use crate::wasm::common::error::ValidationError;
use crate::wasm::common::indices::{FuncIdx, GlobalIdx, LabelIdx, LocalIdx, TableIdx, TypeIdx};
use crate::wasm::common::reader::types::memarg::MemArg;
use crate::wasm::common::reader::types::opcode::*;
use crate::wasm::common::reader::types::BlockType;
use crate::wasm::common::reader::{WasmReadable, WasmReader};

#[derive(Debug, Clone, PartialEq)]
pub enum Instruction {
    I32Const(i32),
    I64Const(i64),
    F32Const(f32),
    F64Const(f64),
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,
    I32Eqz,
    I64Eqz,
    I32Clz,
    I32Ctz,
    I32Popcnt,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,
    LocalGet(LocalIdx),
    LocalSet(LocalIdx),
    LocalTee(LocalIdx),
    GlobalGet(GlobalIdx),
    GlobalSet(GlobalIdx),
    I32Load(MemArg),
    I32Load8S(MemArg),
    I32Load8U(MemArg),
    I32Load16S(MemArg),
    I32Load16U(MemArg),
    I64Load(MemArg),
    I64Load8S(MemArg),
    I64Load8U(MemArg),
    I64Load16S(MemArg),
    I64Load16U(MemArg),
    I64Load32S(MemArg),
    I64Load32U(MemArg),
    F32Load(MemArg),
    F64Load(MemArg),
    I32Store(MemArg),
    I32Store8(MemArg),
    I32Store16(MemArg),
    I64Store(MemArg),
    I64Store8(MemArg),
    I64Store16(MemArg),
    I64Store32(MemArg),
    F32Store(MemArg),
    F64Store(MemArg),
    Call(FuncIdx),
    CallIndirect(TypeIdx, TableIdx),
    Block(BlockType),
    Loop(BlockType),
    If(BlockType),
    Else,
    End,
    Br(LabelIdx),
    BrIf(LabelIdx),
    BrTable(Vec<LabelIdx>, LabelIdx),
    Return,
    Drop,
    Nop,
    Unreachable,
    Select,
    MemorySize,
    MemoryGrow,
    I32WrapI64,
    I64ExtendI32S,
    I64ExtendI32U,
    I32Extend8S,
    I32Extend16S,
    I64Extend8S,
    I64Extend16S,
    I64Extend32S,
    F32Add,
    F32Sub,
    F32Mul,
    F32Div,
    F32Eq,
    F32Ne,
    F32Lt,
    F32Gt,
    F32Le,
    F32Ge,
    F64Eq,
    F64Ne,
    F64Lt,
    F64Gt,
    F64Le,
    F64Ge,
    F32Abs,
    F32Neg,
    F32Sqrt,
    F32Ceil,
    F32Floor,
    F32Trunc,
    F32Nearest,
    F32Min,
    F32Max,
    F32Copysign,
    F64Add,
    F64Sub,
    F64Mul,
    F64Div,
    F64Abs,
    F64Neg,
    F64Sqrt,
    F64Ceil,
    F64Floor,
    F64Trunc,
    F64Nearest,
    F64Min,
    F64Max,
    F64Copysign,
    I32TruncF32S,
    I32TruncF32U,
    I32TruncF64S,
    I32TruncF64U,
    I64TruncF32S,
    I64TruncF32U,
    I64TruncF64S,
    I64TruncF64U,
    F32ConvertI32S,
    F32ConvertI32U,
    F32ConvertI64S,
    F32ConvertI64U,
    F64ConvertI32S,
    F64ConvertI32U,
    F64ConvertI64S,
    F64ConvertI64U,
    F32DemoteF64,
    F64PromoteF32,
    I32ReinterpretF32,
    I64ReinterpretF64,
    F32ReinterpretI32,
    F64ReinterpretI64,
    RefNull(crate::wasm::common::reader::types::RefType),
    RefIsNull,
    TableGet(TableIdx),
    TableSet(TableIdx),
    TableSize(TableIdx),
    TableGrow(TableIdx),
    TableFill(TableIdx),
    Try(BlockType),
    Catch(u32),
    CatchAll,
    Delegate(LabelIdx),
    Throw(u32),
    Rethrow(LabelIdx),
    ReturnCall(FuncIdx),
    ReturnCallIndirect(TypeIdx, TableIdx),
    CallRef(TypeIdx),
    ReturnCallRef(TypeIdx),
    Atomic(u32),
    Gc(u32),
    FcExtension(u32),
    FdExtension(u32),
}

impl WasmReadable for Instruction {
    fn read(wasm: &mut WasmReader) -> Result<Self, ValidationError> {
        let opcode = wasm.read_u8()?;
        match opcode {
            UNREACHABLE => Ok(Instruction::Unreachable),
            NOP => Ok(Instruction::Nop),
            BLOCK => Ok(Instruction::Block(BlockType::read(wasm)?)),
            LOOP => Ok(Instruction::Loop(BlockType::read(wasm)?)),
            IF => Ok(Instruction::If(BlockType::read(wasm)?)),
            ELSE => Ok(Instruction::Else),
            TRY => Ok(Instruction::Try(BlockType::read(wasm)?)),
            CATCH => Ok(Instruction::Catch(wasm.read_var_u32()?)),
            CATCH_ALL => Ok(Instruction::CatchAll),
            DELEGATE => Ok(Instruction::Delegate(wasm.read_var_u32()? as LabelIdx)),
            THROW => Ok(Instruction::Throw(wasm.read_var_u32()?)),
            RETHROW => Ok(Instruction::Rethrow(wasm.read_var_u32()? as LabelIdx)),
            END => Ok(Instruction::End),
            BR => Ok(Instruction::Br(wasm.read_var_u32()? as LabelIdx)),
            BR_IF => Ok(Instruction::BrIf(wasm.read_var_u32()? as LabelIdx)),
            BR_TABLE => {
                let targets = wasm.read_vec(|w| w.read_var_u32().map(|v| v as LabelIdx))?;
                let default = wasm.read_var_u32()? as LabelIdx;
                Ok(Instruction::BrTable(targets, default))
            }
            RETURN => Ok(Instruction::Return),
            CALL => Ok(Instruction::Call(wasm.read_var_u32()? as FuncIdx)),
            CALL_INDIRECT => {
                let ty = wasm.read_var_u32()? as TypeIdx;
                let tab = wasm.read_var_u32()? as TableIdx;
                Ok(Instruction::CallIndirect(ty, tab))
            }
            RETURN_CALL => Ok(Instruction::ReturnCall(wasm.read_var_u32()? as FuncIdx)),
            RETURN_CALL_INDIRECT => {
                let ty = wasm.read_var_u32()? as TypeIdx;
                let tab = wasm.read_var_u32()? as TableIdx;
                Ok(Instruction::ReturnCallIndirect(ty, tab))
            }
            CALL_REF => Ok(Instruction::CallRef(wasm.read_var_u32()? as TypeIdx)),
            RETURN_CALL_REF => Ok(Instruction::ReturnCallRef(wasm.read_var_u32()? as TypeIdx)),
            DROP => Ok(Instruction::Drop),
            SELECT => Ok(Instruction::Select),
            LOCAL_GET => Ok(Instruction::LocalGet(wasm.read_var_u32()? as LocalIdx)),
            LOCAL_SET => Ok(Instruction::LocalSet(wasm.read_var_u32()? as LocalIdx)),
            LOCAL_TEE => Ok(Instruction::LocalTee(wasm.read_var_u32()? as LocalIdx)),
            GLOBAL_GET => Ok(Instruction::GlobalGet(wasm.read_var_u32()? as GlobalIdx)),
            GLOBAL_SET => Ok(Instruction::GlobalSet(wasm.read_var_u32()? as GlobalIdx)),
            I32_LOAD => Ok(Instruction::I32Load(MemArg::read(wasm)?)),
            I64_LOAD => Ok(Instruction::I64Load(MemArg::read(wasm)?)),
            F32_LOAD => Ok(Instruction::F32Load(MemArg::read(wasm)?)),
            F64_LOAD => Ok(Instruction::F64Load(MemArg::read(wasm)?)),
            I32_LOAD8_S => Ok(Instruction::I32Load8S(MemArg::read(wasm)?)),
            I32_LOAD8_U => Ok(Instruction::I32Load8U(MemArg::read(wasm)?)),
            I32_LOAD16_S => Ok(Instruction::I32Load16S(MemArg::read(wasm)?)),
            I32_LOAD16_U => Ok(Instruction::I32Load16U(MemArg::read(wasm)?)),
            I64_LOAD8_S => Ok(Instruction::I64Load8S(MemArg::read(wasm)?)),
            I64_LOAD8_U => Ok(Instruction::I64Load8U(MemArg::read(wasm)?)),
            I64_LOAD16_S => Ok(Instruction::I64Load16S(MemArg::read(wasm)?)),
            I64_LOAD16_U => Ok(Instruction::I64Load16U(MemArg::read(wasm)?)),
            I64_LOAD32_S => Ok(Instruction::I64Load32S(MemArg::read(wasm)?)),
            I64_LOAD32_U => Ok(Instruction::I64Load32U(MemArg::read(wasm)?)),
            I32_STORE => Ok(Instruction::I32Store(MemArg::read(wasm)?)),
            I64_STORE => Ok(Instruction::I64Store(MemArg::read(wasm)?)),
            F32_STORE => Ok(Instruction::F32Store(MemArg::read(wasm)?)),
            F64_STORE => Ok(Instruction::F64Store(MemArg::read(wasm)?)),
            I32_STORE8 => Ok(Instruction::I32Store8(MemArg::read(wasm)?)),
            I32_STORE16 => Ok(Instruction::I32Store16(MemArg::read(wasm)?)),
            I64_STORE8 => Ok(Instruction::I64Store8(MemArg::read(wasm)?)),
            I64_STORE16 => Ok(Instruction::I64Store16(MemArg::read(wasm)?)),
            I64_STORE32 => Ok(Instruction::I64Store32(MemArg::read(wasm)?)),
            REF_NULL => Ok(Instruction::RefNull(crate::wasm::common::reader::types::RefType::read(wasm)?)),
            REF_IS_NULL => Ok(Instruction::RefIsNull),
            MEMORY_SIZE => {
                wasm.read_u8()?;
                Ok(Instruction::MemorySize)
            }
            MEMORY_GROW => {
                wasm.read_u8()?;
                Ok(Instruction::MemoryGrow)
            }
            I32_CONST => Ok(Instruction::I32Const(wasm.read_var_i32()?)),
            I64_CONST => Ok(Instruction::I64Const(wasm.read_var_i64()?)),
            F32_CONST => Ok(Instruction::F32Const(f32::from_bits(wasm.read_f32()?))),
            F64_CONST => Ok(Instruction::F64Const(f64::from_bits(wasm.read_f64()?))),
            I32_EQZ => Ok(Instruction::I32Eqz),
            I32_CLZ => Ok(Instruction::I32Clz),
            I32_CTZ => Ok(Instruction::I32Ctz),
            I32_POPCNT => Ok(Instruction::I32Popcnt),
            I32_EQ => Ok(Instruction::I32Eq),
            I32_NE => Ok(Instruction::I32Ne),
            I32_LT_S => Ok(Instruction::I32LtS),
            I32_LT_U => Ok(Instruction::I32LtU),
            I32_GT_S => Ok(Instruction::I32GtS),
            I32_GT_U => Ok(Instruction::I32GtU),
            I32_LE_S => Ok(Instruction::I32LeS),
            I32_LE_U => Ok(Instruction::I32LeU),
            I32_GE_S => Ok(Instruction::I32GeS),
            I32_GE_U => Ok(Instruction::I32GeU),
            I64_EQZ => Ok(Instruction::I64Eqz),
            I64_EQ => Ok(Instruction::I64Eq),
            I64_NE => Ok(Instruction::I64Ne),
            I64_LT_S => Ok(Instruction::I64LtS),
            I64_LT_U => Ok(Instruction::I64LtU),
            I64_GT_S => Ok(Instruction::I64GtS),
            I64_GT_U => Ok(Instruction::I64GtU),
            I64_LE_S => Ok(Instruction::I64LeS),
            I64_LE_U => Ok(Instruction::I64LeU),
            I64_GE_S => Ok(Instruction::I64GeS),
            I64_GE_U => Ok(Instruction::I64GeU),
            F32_EQ => Ok(Instruction::F32Eq),
            F32_NE => Ok(Instruction::F32Ne),
            F32_LT => Ok(Instruction::F32Lt),
            F32_GT => Ok(Instruction::F32Gt),
            F32_LE => Ok(Instruction::F32Le),
            F32_GE => Ok(Instruction::F32Ge),
            F64_EQ => Ok(Instruction::F64Eq),
            F64_NE => Ok(Instruction::F64Ne),
            F64_LT => Ok(Instruction::F64Lt),
            F64_GT => Ok(Instruction::F64Gt),
            F64_LE => Ok(Instruction::F64Le),
            F64_GE => Ok(Instruction::F64Ge),
            I32_ADD => Ok(Instruction::I32Add),
            I32_SUB => Ok(Instruction::I32Sub),
            I32_MUL => Ok(Instruction::I32Mul),
            I32_DIV_S => Ok(Instruction::I32DivS),
            I32_DIV_U => Ok(Instruction::I32DivU),
            I32_REM_S => Ok(Instruction::I32RemS),
            I32_REM_U => Ok(Instruction::I32RemU),
            I32_AND => Ok(Instruction::I32And),
            I32_OR => Ok(Instruction::I32Or),
            I32_XOR => Ok(Instruction::I32Xor),
            I32_SHL => Ok(Instruction::I32Shl),
            I32_SHR_S => Ok(Instruction::I32ShrS),
            I32_SHR_U => Ok(Instruction::I32ShrU),
            I32_ROTL => Ok(Instruction::I32Rotl),
            I32_ROTR => Ok(Instruction::I32Rotr),
            I64_ADD => Ok(Instruction::I64Add),
            I64_SUB => Ok(Instruction::I64Sub),
            I64_MUL => Ok(Instruction::I64Mul),
            I64_DIV_S => Ok(Instruction::I64DivS),
            I64_DIV_U => Ok(Instruction::I64DivU),
            I64_REM_S => Ok(Instruction::I64RemS),
            I64_REM_U => Ok(Instruction::I64RemU),
            I64_CLZ => Ok(Instruction::I64Clz),
            I64_CTZ => Ok(Instruction::I64Ctz),
            I64_POPCNT => Ok(Instruction::I64Popcnt),
            I64_AND => Ok(Instruction::I64And),
            I64_OR => Ok(Instruction::I64Or),
            I64_XOR => Ok(Instruction::I64Xor),
            I64_SHL => Ok(Instruction::I64Shl),
            I64_SHR_S => Ok(Instruction::I64ShrS),
            I64_SHR_U => Ok(Instruction::I64ShrU),
            I64_ROTL => Ok(Instruction::I64Rotl),
            I64_ROTR => Ok(Instruction::I64Rotr),
            F32_ABS => Ok(Instruction::F32Abs),
            F32_NEG => Ok(Instruction::F32Neg),
            F32_CEIL => Ok(Instruction::F32Ceil),
            F32_FLOOR => Ok(Instruction::F32Floor),
            F32_TRUNC => Ok(Instruction::F32Trunc),
            F32_NEAREST => Ok(Instruction::F32Nearest),
            F32_SQRT => Ok(Instruction::F32Sqrt),
            F32_ADD => Ok(Instruction::F32Add),
            F32_SUB => Ok(Instruction::F32Sub),
            F32_MUL => Ok(Instruction::F32Mul),
            F32_DIV => Ok(Instruction::F32Div),
            F32_MIN => Ok(Instruction::F32Min),
            F32_MAX => Ok(Instruction::F32Max),
            F32_COPYSIGN => Ok(Instruction::F32Copysign),
            F64_ABS => Ok(Instruction::F64Abs),
            F64_NEG => Ok(Instruction::F64Neg),
            F64_CEIL => Ok(Instruction::F64Ceil),
            F64_FLOOR => Ok(Instruction::F64Floor),
            F64_TRUNC => Ok(Instruction::F64Trunc),
            F64_NEAREST => Ok(Instruction::F64Nearest),
            F64_SQRT => Ok(Instruction::F64Sqrt),
            F64_ADD => Ok(Instruction::F64Add),
            F64_SUB => Ok(Instruction::F64Sub),
            F64_MUL => Ok(Instruction::F64Mul),
            F64_DIV => Ok(Instruction::F64Div),
            F64_MIN => Ok(Instruction::F64Min),
            F64_MAX => Ok(Instruction::F64Max),
            F64_COPYSIGN => Ok(Instruction::F64Copysign),
            I32_WRAP_I64 => Ok(Instruction::I32WrapI64),
            I32_TRUNC_F32_S => Ok(Instruction::I32TruncF32S),
            I32_TRUNC_F32_U => Ok(Instruction::I32TruncF32U),
            I32_TRUNC_F64_S => Ok(Instruction::I32TruncF64S),
            I32_TRUNC_F64_U => Ok(Instruction::I32TruncF64U),
            I64_EXTEND_I32_S => Ok(Instruction::I64ExtendI32S),
            I64_EXTEND_I32_U => Ok(Instruction::I64ExtendI32U),
            I64_TRUNC_F32_S => Ok(Instruction::I64TruncF32S),
            I64_TRUNC_F32_U => Ok(Instruction::I64TruncF32U),
            I64_TRUNC_F64_S => Ok(Instruction::I64TruncF64S),
            I64_TRUNC_F64_U => Ok(Instruction::I64TruncF64U),
            F32_CONVERT_I32_S => Ok(Instruction::F32ConvertI32S),
            F32_CONVERT_I32_U => Ok(Instruction::F32ConvertI32U),
            F32_CONVERT_I64_S => Ok(Instruction::F32ConvertI64S),
            F32_CONVERT_I64_U => Ok(Instruction::F32ConvertI64U),
            F32_DEMOTE_F64 => Ok(Instruction::F32DemoteF64),
            F64_CONVERT_I32_S => Ok(Instruction::F64ConvertI32S),
            F64_CONVERT_I32_U => Ok(Instruction::F64ConvertI32U),
            F64_CONVERT_I64_S => Ok(Instruction::F64ConvertI64S),
            F64_CONVERT_I64_U => Ok(Instruction::F64ConvertI64U),
            F64_PROMOTE_F32 => Ok(Instruction::F64PromoteF32),
            I32_REINTERPRET_F32 => Ok(Instruction::I32ReinterpretF32),
            I64_REINTERPRET_F64 => Ok(Instruction::I64ReinterpretF64),
            F32_REINTERPRET_I32 => Ok(Instruction::F32ReinterpretI32),
            F64_REINTERPRET_I64 => Ok(Instruction::F64ReinterpretI64),
            I32_EXTEND8_S => Ok(Instruction::I32Extend8S),
            I32_EXTEND16_S => Ok(Instruction::I32Extend16S),
            I64_EXTEND8_S => Ok(Instruction::I64Extend8S),
            I64_EXTEND16_S => Ok(Instruction::I64Extend16S),
            I64_EXTEND32_S => Ok(Instruction::I64Extend32S),
            TABLE_GET => Ok(Instruction::TableGet(wasm.read_var_u32()? as TableIdx)),
            TABLE_SET => Ok(Instruction::TableSet(wasm.read_var_u32()? as TableIdx)),
            ATOMIC_PREFIX => Ok(Instruction::Atomic(wasm.read_var_u32()?)),
            GC_PREFIX | GC_PREFIX_ALT => Ok(Instruction::Gc(wasm.read_var_u32()?)),
            FC_EXTENSIONS => Ok(Instruction::FcExtension(wasm.read_var_u32()?)),
            FD_EXTENSIONS => Ok(Instruction::FdExtension(wasm.read_var_u32()?)),
            _ => Err(ValidationError::InvalidInstr(opcode)),
        }
    }
}