[package]
name = "std"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = ["userland", "global_allocator"]
userland = []
global_allocator = []

[dependencies]
talc = { version = "4.4.2", default-features = false }
spin = { version = "0.9.8", default-features = false, features = ["mutex", "rwlock", "spin_mutex"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
