#[macro_use]
mod log_wrapper;
pub mod core;
pub mod component;
pub mod execution;
pub mod wasi;
pub mod validation;
pub mod aot;
pub use core::error::ValidationError;
pub use core::reader::span::Span;
pub use core::reader::types::data::DataSegment;
pub use core::reader::types::element::ElemType;
pub use core::reader::types::export::ExportDesc;
pub use core::reader::types::global::GlobalType;
pub use core::reader::types::import::ImportDesc;
pub use core::reader::types::{Limits, NumType, RefType, ValType};
pub use execution::checked;
pub use execution::checked::{Stored, StoredExternVal};
pub use execution::error::{RuntimeError, TrapError};
pub use execution::linker::Linker;
pub use execution::store::ExternVal;
pub use execution::store::Store;
pub use execution::value::Value;
pub use validation::{validate, ValidationInfo};
